IIIF : Deliverable 4 - APPENDIX B: image processing workflow
============================================================
Bart Debunne <bart.debunne@meemoo.be>
1, 17-05-2021
:Revision: 1
:nofooter:
:imagesdir: images
:source-highlighter: rouge
// fix missing admonition icons on Github
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
// configure TOC
:toc:
:toc-placement!:
:toclevels: 3
:showtitle:
:toc-title: Inhoudsopgave

toc::[]

'''''

== Doelstelling

== Image specs

CAUTION: Voor afgeleide bestanden moet onderscheid worden gemaakt tussen werken in public domain en werken die nog onder het auteursrecht vallen. In de overeenkomst die de VKC momenteel met de auteursrechtenorganisatie Sabam heeft, worden volgende hergebruiksvoorwaarden vooropgesteld voor werken die onder het auteursrecht vallen: de resolutie van het gereproduceerde beeld mag niet meer dan 640x480 pixels zijn en een resolutie van maximum 72dpi hebben. Onderstaande specificaties hebben betrekking op werken die niet onder die overeenkomst vallen.

====
* jpeg-2000 (jp2)
* 300 ppi
* sRGB
* Bestanden worden bijgesneden (_crop_), randinformatie zoals kleurkaarten en kaders verwijderd
* Embedded metadata(XMP, Exif, ICC) wordt indien aanwezig overgenomen van het origineel
====

=== Resampling vs resizing vs ...

De te ontsluiten collectie is zowel qua type als qua fysieke afmeting zeer divers, voor de hele VKC-collectie spreken we over heel kleine objecten van een paar centimeter tot wandtapijten, of een wandkaart van ettelijke meters hoog en breed. De afmeting in pixels van het digitale beeld is niet per se in verhouding en is afhankelijk van de leeftijd, de fotograaf, het opnametoestel, etc. Voor sommige grote werken zijn verschillende foto's aan elkaar geplakt (stitching). Andere zijn gevat in 1 foto. Relatief gesproken kan een groter fysiek werk in aantal pixels kleiner of gelijk zijn aan een fysiek kleiner werk.

Om te vermijden dat (heel) grote werken te fel herschaald worden ten opzichte van kleine werken met een in verhouding hoger aantal pixels, zal binnen dit project bekeken worden in welke mate een relatie bestaat tussen de fysieke en digitale afmetingen op basis waarvan herschaling dynamisch kan gebeuren. We onderzoeken dit aan de hand vaan een aantal typewerken zoals _Pierrot et Squelette en Jaune_ van James Ensor.

== Workflow

.Voorbeeld manuele workflow voor creatie van jp2 afgeleide beeldbestanden
image::iiif-jp2-derived-image-workflow.svg[link="https://cawemo.com/share/d893035f-bdbc-419b-9524-e9ff161992d7",alt="workflow voor creatie afgeleiden als jp2"]

Voor de creatie van de afgeleiden starten we met een vrij manuele workflow die eenvoudig kan bijgesteld worden om uiteindelijk te komen tot een  automatiseerbare workflow.
Om zowel de workflow voor de creatie van afgeleide beelden als de specificaties an sich te testen beperken we ons in eerste instantie tot de omzetting van de beelden die nu reeds beschikbaar zijn in de IIIF-viewer in de VKC Arthub. Hierbij zal worden onderzocht welke een haalbare workflow is voor de aanmaak van de afgeleide beeldbestanden en in welke mate dit proces geautomatiseerd kan worden. Indien nodig kunnen bovenstaande specificaties dan ook bijgewerkt worden op basis van voortschrijdend inzicht.

=== Taken

De workflow kan gezien worden als een ETL.

==== Extract

Exporteer de originele tiff-bestanden van tape naar lokale disk. Op basis van een of meerdere pids (external_id).

In deze fase doen we eenmalig een export van de beelden die nu reeds ontsloten worden via de VKC Arthub, vb. https://arthub.vlaamsekunstcollectie.be/nl/catalog/mskgent:1907-A, naar disk. Van daaruit kunnen dan een of meer bestanden naar een werkfolder gekopieerd worden om de workflow te bouwen en te testen, zonder dat de originele bestanden telkens opnieuw geëxporteerd moeten worden.

Te onderzoeken hoe in een productieomgeving dit getriggered kan worden. Bijvoorbeeld door plaatsen van een metadata flag in MAM waardoor export naar een watch_folder on disk en de rest van de workflow automatisch getriggerd kan worden.

==== Transform

===== Detect en crop kleurenkaart

Voor het detecteren van de kleurenkaart maken we gebruik van de colorchecker zoals ontwikkeled voor het Flore de Gand project. Wanneer een kleurenkaart wordt herkend dan wordt de afbeelding bijgesneden en opgeslaan.

Zie: https://github.com/tckrishna/colorchecker.git

[quote]
The code is such that, when an input image is provided, it would perform detections and crop out the colour scale so that only the painting would be saved.

Documentatie en tutorial op: https://colab.research.google.com/drive/1OreAxCrCTkTqbIxu2Z_8KWuCujKyyncI?usp=sharing

===== Resize

`TODO` Analyse nodig van de ratio fysieke afmeting tgo afmeting in pixels.

https://pillow.readthedocs.io/en/stable/reference/Image.html

===== Detect and set Color Profile

In de volgende stap `kdu_compress` wordt het kleurenprofiel vervangen door de value voor `-jp2_space`. Het is echter onduidelijk of dit ook daadwerkelijk het bestand omzet naar dit profiel. En of dit ook geldt wanneer een afbeelding geen kleurenprofiel heeft.

Zoniet moet eerst gedetecteerd worden of er een profile aanwezig is en zoniet moet dit worden gezet als `sRGB`.

===== Encode

Voor het comprimeren en opslaan als jp2 gebruiken we de Kakadu software (binaries) waarvoor we een license hebben.

[source]
kdu_compress -i input.tif -o output.jp2 Clevels=6 Clayers=6 "Cprecincts={256,256},{256,256},{128,128}" "Stiles={512,512}" Corder=RPCL ORGgen_plt=yes ORGtparts=R "Cblk={64,64}" -jp2_space "sRGB" Cuse_sop=yes Cuse_eph=yes -flush_period 1024 Creversible=no -rate 3

IMPORTANT: The JPEG 2000 format supports only a restricted set of ICC Profile features.
The -jp2_space parameter on kdu_compress sets the colour profile in the image metadata, but does not otherwise convert the image - the pixel values remain the same. The sRGB value sets the colour profile to the sRGB IEC61966-2.1 profile. (This is not the only way to set the colour profile)
Kakadu (and JP2 itself) will not support CYMK images:
Only three colour channels, R (red), G (green) and B (blue), are supported by the JP2 file format.
For example the sRGB v4 ICC preference profile is not supported, and cannot be embedded into a JP2 file using Kakadu. Setting -jp2_space sRGB on kdu_compress will erase the embedded profile and so allow it to be converted. The sRGB IEC61966-2.1 profile thus assigned is sufficiently different that in some cases there is a noticeable tint to the created JP2.
_https://readthedocs.org/projects/image-processing/downloads/pdf/latest/_


===== Copy metadata

kdu_compress kopieert niet alle metadata tags.

Suggestie: copy (all) tags from src to dest, met exiftool
https://manpages.ubuntu.com/manpages/artful/man1/exiftool.1p.html#copying%20examples

===== Test en validate

Test:

* ppi => 300
* icc => sRGB
* iptc, xmp same as source
* valid jp2

https://jpylyzer.openpreservation.org
https://github.com/openpreserve/jpylyzer
https://exiftool.org/index.html
https://exiftool.org/exiftool_pod.html



==== Load

Bestanden worden naar een dest folder gekopieerd waar ze steekproefsgewijs visueel geïnspecteerd kunnen worden.

De folder doet ook dienst als media mount of fodler voor de IIPImage server.

==== Clean

Remove intermediary and temp files

== Technische specs

* Scripting: Python
* Metadata: exiftool
* JP2-encode: kdu_compress
* JP2-validaty: jpylyzer
* Tests: ?
* Orchestartion: Airflow?

== Infrastructuur

DEV: lokaal
QAS en PRD: VM +data